import { configDotenv } from "dotenv";

configDotenv();

export const env = Object.freeze({
  EMRPDH_OKTA_CLIENT_ID: process.env.EMRPDH_OKTA_CLIENT_ID,
  EMRPDH_OKTA_ISSUER: process.env.EMRPDH_OKTA_ISSUER,
  EMRPDH_OKTA_DOMAIN: process.env.EMRPDH_OKTA_DOMAIN,
  EMRPDH_OKTA_TOEKN: process.env.EMRPDH_OKTA_TOEKN,

  EMRPDH_SERVER_DB_URI: process.env.EMRPDH_SERVER_DB_URI,
  EMRPDH_SERVER_DB_AUTHKEY: process.env.EMRPDH_SERVER_DB_AUTHKEY,
  EMRPDH_SERVER_DB_DATABASEID: process.env.EMRPDH_SERVER_DB_DATABASEID,

  MULE_OKTA_DOMAIN: process.env.MULE_OKTA_DOMAIN,
  MULE_OKTA_ISSUER: process.env.MULE_OKTA_ISSUER,
  MULE_OKTA_DEFAULT_SCOPE: process.env.MULE_OKTA_DEFAULT_SCOPE,
  MULE_OKTA_CLIENT_ID: process.env.MULE_OKTA_CLIENT_ID,
  MULE_OKTA_CLIENT_SECRET: process.env.MULE_OKTA_CLIENT_SECRET,

  NODE_APP_MULSOFT_API_URL: process.env.NODE_APP_MULSOFT_API_URL,
  NODE_APP_MULESOFT_ENRYPT_KEY_VALUE:
    process.env.NODE_APP_MULESOFT_ENRYPT_KEY_VALUE,
  NODE_APP_MULESOFT_ENRYPT_INIT_VECTOR_VALUE:
    process.env.NODE_APP_MULESOFT_ENRYPT_INIT_VECTOR_VALUE,

  NODE_APP_MULESOFT_API_ITEM_CLIENT_ID:
    process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_ID,
  NODE_APP_MULESOFT_API_ITEM_CLIENT_ID_VALUE:
    process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_ID_VALUE,
  NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET:
    process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET,

  NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET_VALUE:
    process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET_VALUE,
  NODE_APP_MULESOFT_API_SPEC_CLIENT_ID:
    process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_ID,
  NODE_APP_MULESOFT_API_SPEC_CLIENT_ID_VALUE:
    process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_ID_VALUE,
  NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET:
    process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET,

  NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET_VALUE:
    process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET_VALUE,
  NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID:
    process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID,
  NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID_VALUE:
    process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID_VALUE,
  NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET:
    process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET,

  NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET_VALUE:
    process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET_VALUE,
  NODE_APP_MULESOFT_API_BOM_CLIENT_ID:
    process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_ID,
  NODE_APP_MULESOFT_API_BOM_CLIENT_ID_VALUE:
    process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_ID_VALUE,
  NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET:
    process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET,

  NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET_VALUE:
    process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET_VALUE,

  ENOVIA_API_URL: process.env.ENOVIA_API_URL,
  ENOVIA_CLOUD_API_URL: process.env.ENOVIA_CLOUD_API_URL,
  NODE_APP_PLM_API_KEY: process.env.NODE_APP_PLM_API_KEY,
  NODE_APP_PLM_API_KEY_VALUE: process.env.NODE_APP_PLM_API_KEY_VALUE,

  NODE_APP_LIFECYCLEPROCESS_LOGS: process.env.NODE_APP_LIFECYCLEPROCESS_LOGS,

  NODE_API_TENANT_ID: process.env.NODE_API_TENANT_ID,

  SERVER_MODE_ENV: process.env.SERVER_MODE_ENV ?? "dev",

  SAAS_BASE_URL: process.env.SAAS_BASE_URL,
  SAAS_LOGIN_URL: process.env.SAAS_LOGIN_URL,
  SAAS_CSRF_URL: process.env.SAAS_CSRF_URL,
  SAAS_AUTH_PARAM_URL: process.env.SAAS_AUTH_PARAM_URL,

  EMRPDH_NODE_URL: process.env.EMRPDH_NODE_URL,

  bomCommon: {
    JDI_BOM_BASE_URL: process.env.JDI_BOM_BASE_URL,
    JDI_BOM_SYSTEM_INFO_URL: process.env.JDI_BOM_SYSTEM_INFO_URL,

    JDI_BOM_CLIENT_ID: process.env.JDI_BOM_CLIENT_ID,
    JDI_BOM_CLIENT_SECRET: process.env.JDI_BOM_CLIENT_SECRET,
    JDI_BOM_SENDER_ID: process.env.JDI_BOM_SENDER_ID,
    JDI_BOM_COMMON_TARGET_ID: process.env.JDI_BOM_COMMON_TARGET_ID,
    JDI_BOM_BUSINESS_GROUP: process.env.JDI_BOM_BUSINESS_GROUP,

    JDI_BOM_STATUS_CLIENT_ID: process.env.JDI_BOM_STATUS_CLIENT_ID,
    JDI_BOM_STATUS_CLIENT_SECRET: process.env.JDI_BOM_STATUS_CLIENT_SECRET,
    JDI_BOM_STATUS_TARGET_ID: process.env.JDI_BOM_STATUS_TARGET_ID,
  },

  smtp: {
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_EMAIL: process.env.SMTP_EMAIL,
    SMTP_PASSWORD: process.env.SMTP_PASSWORD,
  },
} as const);
