import {
    ENOVIA_API_URL,
    NODE_APP_MULSOFT_API_URL,
    ENOVIA_CLOUD_API_URL,
    NODE_APP_ENOVIA_API_HEADER
} from "./index";

const APIBASEURL = {
    "onPrem": {
        "headerData": NODE_APP_ENOVIA_API_HEADER,
        "searchCA": `${ENOVIA_API_URL}/erp/findObjects`,
        "getCARelatedMco": `${ENOVIA_API_URL}/mco/CAid`,
        "searchMCO": `${ENOVIA_API_URL}/erp/findObjects`,
        "getMCOdetailById": `${ENOVIA_API_URL}/productHierarchy/classes`,
        "updateMCOdetails": `${ENOVIA_API_URL}/productHierarchy/classify`,
        "validationByMcoId": `${ENOVIA_API_URL}/mco/validate`,
        "getItemDetailsByMcoId": `${ENOVIA_API_URL}/erp/item`,
        "getBomDetailsByMcoId": `${ENOVIA_API_URL}/mco/bom`,
        "changeStateByMcoId": `${ENOVIA_API_URL}/mco/changeState`,
        "updateMCOData": `${ENOVIA_API_URL}/mco/updateMCOData`,
        "getDataForClassificationByMCONames": `${ENOVIA_API_URL}/mco/getDataForClassificationyMCONames/mcoList`,
        "updateMCOObjects": `${ENOVIA_API_URL}/mco/updateMCOObjects/mcoList`,
        "getRSMEList": `${ENOVIA_API_URL}/mco/getRSMEs`,
        "getRMEList": `${ENOVIA_API_URL}/mco/getRMEs`,
        "getSpecAssignmentInfo": `${ENOVIA_API_URL}/mco/getSpecDetails`,
        "massUpdatePart": `${ENOVIA_API_URL}/partnumber/updateItemObjects/itemList`,
        "massUpdateDecriptionCheck": `${ENOVIA_API_URL}/partnumber/massUpdateDecriptionCheck/itemList`,
        "getMRbyPartAndPlant": `${ENOVIA_API_URL}/mco/getMRbyPartAndPlant/partList`,
        "updateAttributePartList": `${ENOVIA_CLOUD_API_URL}/mco/updateMR/partList`,
        "getChildnWhereUsedParts": `${ENOVIA_API_URL}/mco/getMRDetailsByPartName/partList`,
        "updateSpecAndObsStatus": `${ENOVIA_API_URL}/partnumber/updateClassificationAttribute/objList`,
        "sendItem": `${NODE_APP_MULSOFT_API_URL}-emrplm-isv-e-item-enovia-v1/api/itemdetails`,
        "sendBom": `${NODE_APP_MULSOFT_API_URL}-emrplm-isv-e-bom-enovia-v1/api/billofmaterial`,
        "sendSpec": `${NODE_APP_MULSOFT_API_URL}-emrplm-isv-e-speccreation-enovia-v1/api/speccreation`,
        "sendSpecAssignment": `${NODE_APP_MULSOFT_API_URL}-emrplm-isv-e-specassignment-enovia-v1/api/specassignment`,
    },
    "SaaS": {
        "headerData": NODE_APP_ENOVIA_API_HEADER,
        "searchCA": `${ENOVIA_CLOUD_API_URL}/erp/findObjects`,
        "getCARelatedMco": `${ENOVIA_CLOUD_API_URL}/mco/CAid`,
        "searchMCO": `${ENOVIA_CLOUD_API_URL}/erp/findObjects`,
        "getMCOdetailById": `${ENOVIA_CLOUD_API_URL}/productHierarchy/classes`,
        "updateMCOdetails": `${ENOVIA_CLOUD_API_URL}/productHierarchy/classify`,
        "validationByMcoId": `${ENOVIA_CLOUD_API_URL}/mco/validate`,
        "getItemDetailsByMcoId": `${ENOVIA_CLOUD_API_URL}/erp/item`,
        "getBomDetailsByMcoId": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-bomcadetails-enovia-v1/api/bomchangeaction`,
        "changeStateByMcoId": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "searchCAandMCO": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "getCADetails": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "mofifyCAMCO": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "promoteDemoteMCO": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "caApprove": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "routeStart": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "taskList": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "taskApproval": `${NODE_APP_MULSOFT_API_URL}-emrplm-e-itemcadetails-enovia-v1/api/changeaction`,
        "updateMCOData": `${ENOVIA_CLOUD_API_URL}/mco/updateMCOData`,
        "getDataForClassificationByMCONames": `${ENOVIA_CLOUD_API_URL}/mco/getDataForClassificationyMCONames/mcoList`,
        "updateMCOObjects": `${ENOVIA_CLOUD_API_URL}/mco/updateMCOObjects/mcoList`,
        "getRSMEList": `${ENOVIA_CLOUD_API_URL}/mco/getRSMEs`,
        "getRMEList": `${ENOVIA_CLOUD_API_URL}/mco/getRMEs`,
        "getSpecAssignmentInfo": `${ENOVIA_CLOUD_API_URL}/mco/getSpecDetails`,
        "sendItem": `${NODE_APP_MULSOFT_API_URL}-emrplm-isv-e-item-enovia-v1/api/itemdetails`,
        "sendBom": `${NODE_APP_MULSOFT_API_URL}-emrplm-isv-e-bom-enovia-v1/api/billofmaterial`,
        "sendSpec": `${ENOVIA_CLOUD_API_URL}-emrplm-isv-e-bom-enovia-v1/api/specassignment`,
    }
};
export { APIBASEURL }