let dotenv = require('dotenv');
dotenv.config();

// Server mode variable
export const SERVER_MODE_ENV: string = process.env.SERVER_MODE_ENV || "";

// static values for testing
export const NODE_APP_MULSOFT_API_URL: string = process.env.NODE_APP_MULSOFT_API_URL || "";
export const NODE_APP_MULESOFT_API_ITEM_CLIENT_ID: string = process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_ID || "";
export const NODE_APP_MULESOFT_API_ITEM_CLIENT_ID_VALUE: string = process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_ID_VALUE || "";
export const NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET: string = process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET || "";
export const NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET_VALUE: string = process.env.NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET_VALUE || "";

export const NODE_APP_MULESOFT_API_SPEC_CLIENT_ID: string = process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_ID || "";
export const NODE_APP_MULESOFT_API_SPEC_CLIENT_ID_VALUE: string = process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_ID_VALUE || "";
export const NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET: string = process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET || "";
export const NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET_VALUE: string = process.env.NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET_VALUE || "";

export const NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID: string = process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID || "";
export const NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID_VALUE: string = process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID_VALUE || "";
export const NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET: string = process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET || "";
export const NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET_VALUE: string = process.env.NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET_VALUE || "";

export const NODE_APP_MULESOFT_API_BOM_CLIENT_ID: string = process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_ID || "";
export const NODE_APP_MULESOFT_API_BOM_CLIENT_ID_VALUE: string = process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_ID_VALUE || "";
export const NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET: string = process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET || "";
export const NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET_VALUE: string = process.env.NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET_VALUE || "";

export const NODE_APP_MULESOFT_ENRYPT_KEY_VALUE = process.env.NODE_APP_MULESOFT_ENRYPT_KEY_VALUE || "";
export const NODE_APP_MULESOFT_ENRYPT_INIT_VECTOR_VALUE = process.env.NODE_APP_MULESOFT_ENRYPT_INIT_VECTOR_VALUE || "";

export const NODE_APP_PLM_API_KEY: string = process.env.NODE_APP_PLM_API_KEY || "";
export const NODE_APP_PLM_API_KEY_VALUE: string = process.env.NODE_APP_PLM_API_KEY_VALUE || "";

export const ENOVIA_API_URL: string = process.env.ENOVIA_API_URL || "";
export const ENOVIA_CLOUD_API_URL: string = process.env.ENOVIA_CLOUD_API_URL || "";

export const NODE_APP_LIFECYCLEPROCESS_LOGS: string = process.env.NODE_APP_LIFECYCLEPROCESS_LOGS || "NO";

export const NODE_APP_MULESOFT_ITEM_API_HEADER = {
    headers: {
        'Content-Type': 'text/plain',
        [NODE_APP_MULESOFT_API_ITEM_CLIENT_ID]: NODE_APP_MULESOFT_API_ITEM_CLIENT_ID_VALUE,
        [NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET]: NODE_APP_MULESOFT_API_ITEM_CLIENT_SECRET_VALUE,
    },
};
export const NODE_APP_MULESOFT_SPEC_API_HEADER = {
    headers: {
        'Content-Type': 'text/plain',
        [NODE_APP_MULESOFT_API_SPEC_CLIENT_ID]: NODE_APP_MULESOFT_API_SPEC_CLIENT_ID_VALUE,
        [NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET]: NODE_APP_MULESOFT_API_SPEC_CLIENT_SECRET_VALUE,
    },
};
export const NODE_APP_MULESOFT_SPEC_ASSIGNMENT_API_HEADER = {
    headers: {
        'Content-Type': 'text/plain',
        [NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID]: NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_ID_VALUE,
        [NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET]: NODE_APP_MULESOFT_API_SPEC_ASSIGNMENT_CLIENT_SECRET_VALUE,
    },
};
export const NODE_APP_MULESOFT_BOM_API_HEADER = {
    headers: {
        'Content-Type': 'text/plain',
        [NODE_APP_MULESOFT_API_BOM_CLIENT_ID]: NODE_APP_MULESOFT_API_BOM_CLIENT_ID_VALUE,
        [NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET]: NODE_APP_MULESOFT_API_BOM_CLIENT_SECRET_VALUE,
    },
};
export const NODE_APP_ENOVIA_API_HEADER = {
    headers: {
        'Content-Type': 'application/json',
        [NODE_APP_PLM_API_KEY]: NODE_APP_PLM_API_KEY_VALUE,
    },
};